routes:

collections:
  /blog/:
    permalink: /blog/{slug}/
    filter: tag:blog  
  /:
    permalink: /{slug}/
    filter: tag:-blog
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
