version: '3'

services:
  ghost:
    image: ghost:3.7.0
    container_name: ghost
    volumes:
      - ${PWD}/..:/var/lib/ghost/content/themes/ieee-ghost:Z
      - ${PWD}/localdata:/var/lib/ghost/content/data:Z
    environment:
      - NODE_ENV=development
    ports:
      - 2368:2368
